version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grafica_pds_nuxt
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3000}
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - grafica_network

  postgres:
    image: postgres:latest
    container_name: grafica_pds_postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-grafica_pds}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - grafica_network

networks:
  grafica_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
