version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: grafica_pds_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: grafica_pds
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - grafica_network

networks:
  grafica_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
